version: '2'
services:
  jenkins:
    container_name: jenkins
    image: ubuntu
    restart: always
    volumes:
      - /etc/jenkins:/var/jenkins_home
    network_mode: bridge
    ports:
      - 8081:8080
      - 50000:50000
    command: >
      bash -c "apt update &&
      apt dist-upgrade -y &&
      apt install --no-install-recommends openjdk-8-jre-headless wget gnupg2 -y apt-transport-https cmake gcc &&
      mkdir -p /var/jenkins_home &&
      cd /var/jenkins_home &&
      rm -rf jenkins.w* &&
      wget http://mirrors.jenkins-ci.org/war-stable/latest/jenkins.war > jenkins.war &&
      chmod 744 /var/jenkins_home/jenkins.war &&
      rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man &&
      java -jar -Xmx512m jenkins.war"
